# Generated by Django 3.2.16 on 2022-11-10 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('genero', models.CharField(max_length=40)),
                ('estreno', models.DateField()),
                ('duracion', models.IntegerField()),
            ],
        ),
    ]
