# Generated by Django 3.2.16 on 2022-11-10 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aventura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('epigrafe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ciencia_Ficcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('epigrafe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Drama',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('epigrafe', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Terror',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=40)),
                ('direccion', models.CharField(max_length=40)),
                ('estreno', models.DateField()),
                ('duracion', models.IntegerField()),
                ('epigrafe', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Pelicula',
        ),
    ]
